name: ng_bootstrap
version: 3.0.0
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=2.11.99 <3.0.0'
dependencies:
  ngdart: ^7.0.0
#  angular:
#    path: ../angular/angular
  js_shims: ^1.0.0
  intl: ^0.17.0
  bootstrap_sass: 
    git: https://github.com/PinguinitoRAwr/bootstrap_sass
#  bootstrap_sass:
#    path: ../bootstrap_sass
  stream_transform: ^2.0.0
  font_awesome: 
    git: https://github.com/PinguinitoRAwr/Font-Awesome
  ngforms: ^4.0.0
#  angular_forms:
#    path: ../angular/angular_forms
dev_dependencies:
  build_runner: any
  sass_builder: ^2.0.0
  lints: ^2.0.1
#  sass_builder:
#    path: ../sass_builder
